# Generated by Django 4.2 on 2025-01-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.istockphoto.com/photos/pizza', max_length=1000),
        ),
    ]
